version: 2

models:
  - name: sales_incremental
    columns:
      - name: invoice_and_item_number
        tests:
          - unique
          - not_null
          # - invoice_number
  - name: stage_sales
  - name: stage_sales_view
  - name: stage_sales_table
  - name: top_10_sales